### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by AntonJakobsson** [neil454/deep-motion#1]
Hi Neil,
Is it possible for you to attach a readme in order to reproduce training of a model? Or can you possibly upload a pretrained model in order to investigate the potential when interpolation of frames using neural networks?

**Comment by neil454** [comment]
Sure thing! I can do both when I get the time, hopefully this weekend.

**Comment by neil454** [comment]
I've updated the readme, ~and added the keras model weights in the weights/ folder.~

EDIT: The model weights are now available in my initial release:
https://github.com/neil454/deep-motion/releases/tag/0.1

For more information about training, I added some more comments in train.py, but for a detailed walkthrough in English, you can look at the paper or the presentation video (both are in the new readme).

Hope this helped!
