### ISSUE TITLE
does deep-motion depends on unspecified configurations or dependencies ?

### ISSUE THREAD

**Issue by GunpowderGuy** [neil454/deep-motion#2]
While trying deep-motion convert I kept getting errors about dependencies not being installed on my computer , despite having installed all the libraries mentioned in the readme , now that seems to be gone , but now i get this.

 GStreamer-CRITICAL **: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed

(python:6153): GStreamer-CRITICAL **: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed
GStreamer: Error opening bin: no source element for URI "/media/neil/Neil's"
Traceback (most recent call last):
  File "fps_convert.py", line 89, in <module>

when trying to run fps convert , the error report mentions a folder in /media , is that something you have in your computer, that the program depends on ?

**Comment by neil454** [comment]
I have not provided the actual training data to train the model (which is what `X_val_KITTI.npy` is). You can download the KITTI dataset with [raw_data_downloader.sh](https://github.com/neil454/deep-motion/blob/master/KITTI_data_download/raw_data_downloader.sh). Training the network should not be too hard as long as you understand how to pre-process the input data (look at train.py for details).

For running `fps_convert.py`, all you need to do is change `vid_dir` and `vid_fn` in `main()`. I could probably make this cleaner with command-line args, but this shouldn't be that hard.

**Comment by GunpowderGuy** [comment]
i had modified my post already , there were more instructions , but i had ignored them

**Comment by GunpowderGuy** [comment]
okay , so my first complain is still up in the air ( i will try to use this in another computer , to see if there are truly additional dependencies )  , the second one was my fault , because i dindn't followed all the instructions , and the third one was really a ( minor ) issue
But after all this how to use neural net for images ( not videos ) is not clear to me and i still have this problem with fps_convert.py

Using TensorFlow backend.
warning: GStreamer: unable to query duration of stream (/builddir/build/BUILD/opencv-3.1.0/modules/videoio/src/cap_gstreamer.cpp:832)
Traceback (most recent call last):
  File "fps_convert.py", line 89, in <module>
    main()
  File "fps_convert.py", line 77, in main
    vid_arr, fps = load_vid(os.path.join(vid_dir, vid_fn))
  File "fps_convert.py", line 31, in load_vid
    vid_arr = np.zeros(shape=(num_frames, 128, 384, 3), dtype="uint8")
ValueError: negative dimensions are not allowed

**Comment by neil454** [comment]
@diegor8 Hmm, for some reason `num_frames` is a negative value. What type of video are you loading? Also, you may need to install OpenCV with FFMPEG support.

**Comment by GunpowderGuy** [comment]
i have both opencv and ffmpeg installed , or you mean a special version of opencv ?

**Comment by neil454** [comment]
I mean before you compile OpenCV, when you configure the cmake build, it should say something like this...
```
Video I/O:
--     FFMPEG:         YES
```

If you installed OpenCV through Anaconda or some other method that didn't require compiling from scratch, it probably doesn't come with FFMPEG support.

Anyways, it is pretty easy to test this, just try loading a .mp4 file with opencv...

```
import cv2

cap = cv2.VideoCapture('vid.mp4')
```

**Comment by GunpowderGuy** [comment]
okay , i am already in the process of doing it  , ( for the record here is a good tutorial :  http://docs.opencv.org/3.1.0/d7/d9f/tutorial_linux_install.html  ) the only thing left would be clearer instructions to use this with pictures , use pre trained training,py  ( or is the only reason it fails to me , is because even using the pre trained weights requires the kitti dataset ? )

**Comment by neil454** [comment]
The easiest way to understand how to use this with images is to look at line 56 of `fps_convert.py`:
```
pred = model.predict(np.expand_dims(np.transpose(np.concatenate((vid_arr[i-1], vid_arr[i]), axis=2)/255., (2, 0, 1)), axis=0))
```

Think of `vid_arr[i-1]` and `vid_arr[i]` as two consecutive frames/images of shape `(128, 384, 3)` each.

First, we use `np.concatenate` to stack the images on top of each other, on their RGB channel dimension, thus making an array of shape `(128, 384, 6)`.

Then, the only pre-processing we do is divide all the image pixel values by 255, to put them in a range from 0.0-1.0.

Finally, to get the input ready for the network, we have to swap the color channel order for use with Theano, so we use `np.transpose(X, (2, 0, 1))` to morph the array into a shape of `(6, 128, 384)` And also use `np.expand_dims` to add an extra dimension at `axis=0`, to make it a shape of `(1, 6, 128, 384)`, which means our "batch size" is 1 for this inference step.

Now our input is ready to pass through the network with model.predict to get our output of shape `(1, 3, 128, 384)` into `pred`.

To post-process our output, we just do the reverse of the steps above, which I do in line 57:
```
new_vid_arr.append((np.transpose(pred[0], (1, 2, 0))*255).astype("uint8"))
```

**Comment by GunpowderGuy** [comment]
having to analyze a piece of software to know how it works is okay , but from the last issue (Reproduce results) i thought that you had already added more extensive documentation

**Comment by robertguetzkow** [comment]
I might have a related problem. Assuming that the supplied weights in the folder are enough to use the existing model (get_unet_2) fps_convert.py should be able to work with a supplied video.
However when I run fps_convert.py with all dependencies installed this happens:

> python fps_convert.py
> Using TensorFlow backend.
> Video loading is 0.0% done.
> Traceback (most recent call last):
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py",
> line 670, in _call_cpp_shape_fn_impl
>     status)
>   File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
>     next(self.gen)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py",
> line 469, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> **tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative**
> **dimension size caused by subtracting 2 from 1 for 'MaxPool_2' (op:**
> **'MaxPool') with input shapes: [?,1,32,128].**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fps_convert.py", line 93, in <module>
>     main()
>   File "fps_convert.py", line 83, in main
>     double_vid_arr = double_vid_fps(vid_arr)
>   File "fps_convert.py", line 45, in double_vid_fps
>     model = get_unet_2((6, 128, 384))
>   File
> "/home/robert/Downloads/SAR/ML/Software/deep-motion-master/src/FI_unet.py",
> line 75, in get_unet_2
>     pool3 = MaxPooling2D(pool_size=(2, 2))(bn3)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/keras/engine/topology.py",
> line 572, in __call__
>     self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/keras/engine/topology.py",
> line 635, in add_inbound_node
>     Node.create_node(self, inbound_layers, node_indices, tensor_indices)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/keras/engine/topology.py",
> line 166, in create_node
>     output_tensors = to_list(outbound_layer.call(input_tensors[0],
> mask=input_masks[0]))
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/keras/layers/pooling.py",
> line 160, in call
>     dim_ordering=self.dim_ordering)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/keras/layers/pooling.py",
> line 210, in _pooling_function
>     pool_mode='max')
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py",
> line 2866, in pool2d
>     x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py",
> line 1793, in max_pool
>     name=name)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py",
> line 1598, in _max_pool
>     data_format=data_format, name=name)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py",
> line 763, in apply_op
>     op_def=op_def)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
> line 2397, in create_op
>     set_shapes_for_outputs(ret)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
> line 1757, in set_shapes_for_outputs
>     shapes = shape_func(op)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py",
> line 1707, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py",
> line 610, in call_cpp_shape_fn
>     debug_python_shape_fn, require_shape_fn)
>   File
> "/home/robert/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py",
> line 675, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> **ValueError: Negative dimension size caused by subtracting 2 from 1 for**
> **'MaxPool_2' (op: 'MaxPool') with input shapes: [?,1,32,128].**
> 

It would be great if you have an idea where things went wrong. It looks like an error in the structure of the model, but that can't be it.

**Comment by neil454** [comment]
Robert, for some reason your comment does not show up on GitHub, weird. (For anyone else, please see the bottom of this post for his question)

Anyways, I'm pretty sure you just need to set Keras's dim ordering to
Theano-style.

Either change the line in ~/.keras/keras.json
from: "image_dim_ordering": "tf",
to: "image_dim_ordering": "th",

or if you only want to do this for my code, just add this code at line 21
of fps_convert.py (before you import get_unet_2):

import keras.backend as K
K.set_image_dim_ordering("th")

**Comment by GunpowderGuy** [comment]
@neil454 what happened with the documentation mentioned in the last issue ? Am i missunderstanding what you were trying to say ? May i compile it myself from all the advice you are giving and the solutions i have come up with to the problems i was having  ?

**Comment by robertguetzkow** [comment]
@neil454 

Thanks for the reply! The comment doesn't show up, because I realized my mistake directly after posting and deleted it. Sorry for that.

In case somebody else has this problem: Tensorflow used a different notation in version 0.10 which was equivalent to Theano. So even if you are using Tensorflow v0.10 you need to set the `image_dim_ordering` to 'th' in Keras' configuration (~/.keras/keras.json) .

**Comment by robertguetzkow** [comment]
@diegor8 

The software works fine when the required dependencies are installed. I think you can close this issue.

**Comment by GunpowderGuy** [comment]
i will , but i will be redacting a guide and post the compiled opencv binaries , to help new people trying to use deep motion

**Comment by Nandan-M-Hegde** [comment]
How much time did it take to train and also what were the hardware components used?
