### ISSUE TITLE
Archive files for model weights possibly corrupt

### ISSUE THREAD

**Issue by robertguetzkow** [neil454/deep-motion#3]
It seems the split zip files containing the model's weights cannot be properly extracted. 
The following command was used to create the merged zip:

> zip -s- weights.zip -O weightsCombined.zip

The resulting zip could not be extracted (it creates a damaged file).

> $ unzip -FF weightsCombo.zip
> Archive:  weightsCombo.zip
>    inflating: weights_unet2_finetune_youtube_100epochs.hdf5
>    error:  invalid compressed data to inflate

Further testing shows that the weights.zip apparently contains no (useful) data. Joining with the another command reveals problems with the file.

> $ zip -FF weights.zip --out weights_fixed.zip
> Fix archive (-FF) - salvage what can
>  Found end record (EOCDR) - says expect 4 splits
> Scanning for entries...
>   Found spanning marker - expected as this is split (multi-disk) archive...
>  copying: weights_unet2_finetune_youtube_100epochs.hdf5  (212788492 bytes)
>        zip warning: entry truncated: weights_unet2_finetune_youtube_100epochs.hdf5
>        zip warning: expected compressed/stored size 212788492, actual 134217621
>        zip warning: unexpected signature 50 4b 0a 0c on disk 2 at 33332149
> 
>        zip warning: skipping this signature...
>        zip warning: unexpected signature 50 4b 0b 06 on disk 2 at 36919392
> 
>        zip warning: skipping this signature...
>        zip warning: unexpected signature 50 4b 03 07 on disk 2 at 59441625
> 
>        zip warning: skipping this signature...
>        zip warning: unexpected signature 50 4b 05 0b on disk 3 at 1861669
> 
>        zip warning: skipping this signature...
> **Central Directory found...**
> **no local entry: weights_unet2_finetune_youtube_100epochs.hdf5**
> **EOCDR found ( 4 11462122)...**
>         **zip warning: zip file empty**

**Comment by GunpowderGuy** [comment]
the zip seems to be empty , but aren't the files next to it (.z1, .z2, .z3 ) the weights you are looking for ?

**Comment by robertguetzkow** [comment]
@diegor8 these files form a whole zip and can't be used separately (as far as I am aware). According to the commit messages this was done to circumvent file size limits.

**Comment by GunpowderGuy** [comment]
i thought that they just had to be copied to the model_weights folder , but not extracted

**Comment by neil454** [comment]
Ok, I just made a Release and uploaded the weights that way. Hopefully this should make things easier...

https://github.com/neil454/deep-motion/releases/tag/0.1

**Comment by GunpowderGuy** [comment]
it says that it was released in january .

**Comment by neil454** [comment]
@diegor8 That's because the last commit was on Jan 25, so the code in the release is from January.

**Comment by GunpowderGuy** [comment]
@neil454 but that hasnt reached the master branch yet

**Comment by robertguetzkow** [comment]
@neil454 
Thank you! Can you confirm that the split archive was broken? Maybe it worked fine with the software you used.

**Comment by neil454** [comment]
It worked for me on Windows using 7-Zip, but I understand split archives can be finicky in other programs.

**Comment by robertguetzkow** [comment]
I have only tested it on Linux (including 7z) and it didn't work . Perhaps I just didn't know a particular trick to get it running over there.

With the release it's definitely easier for everyone.

Thanks again!
