### ISSUE TITLE
Error in get_unet_2 function

### ISSUE THREAD

**Issue by YifeiAI** [neil454/deep-motion#4]
When only run two lines: 
from FI_unet import get_unet_2
model = get_unet_2((6, 128, 384))

it shows error of:
![11](https://cloud.githubusercontent.com/assets/28927927/26411440/3181b978-40a6-11e7-902a-da4c6b56148f.jpg)

when run: 

from FI_unet import get_unet_2
model = get_unet()

it shows error of:
![22](https://cloud.githubusercontent.com/assets/28927927/26411456/3e3b66d2-40a6-11e7-90b3-981e55e44d4a.jpg)

Note that I use:
Python 3.5
Tensorflow 0.10.0
Keras 1.1.2

**Comment by neil454** [comment]
For those who can't see the error images (I can only see them through email), here is the error:

`ValueError: Filter must not be larger than the input: Filter: (3, 3) Input: (1, 32)`

As for the solution, refer to [this comment](https://github.com/neil454/deep-motion/issues/2#issuecomment-283479980).

EDIT: Sorry I accidentally closed this issue. I reopened it just now. Let me know if that solution worked.

**Comment by YifeiAI** [comment]
Thank you neil!  I added those two lines but it shows new error
again when I run:

from FI_unet import get_unet_2
model = get_unet2((6, 128, 384))

![649691890534176536](https://cloud.githubusercontent.com/assets/28927927/26412049/cead9ebe-40a7-11e7-9e99-e63e55a6106d.jpg)
![319038025832799103](https://cloud.githubusercontent.com/assets/28927927/26412054/d118590a-40a7-11e7-8c29-20a6e440c894.jpg)

**Comment by YifeiAI** [comment]
I solved this problem by change 124 line in 
conv10 = Convolution2D(int(input_shape[0]/2), 1, 1, activation='sigmoid')(bn9)

I think this error probably result in the difference between python2.x and python3.x
