### ISSUE TITLE
Problem training

### ISSUE THREAD

**Issue by hussamh10** [neil454/deep-motion#7]
I am facing some problems running the train.py file. I have followed your instructions but an error has occurred regarding the pool4 in get_unet_2. 
Error:
`ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_3/MaxPool' (op: 'MaxPool') with input shapes: [?,1,32,128].`

The input shape I'm using is the same as you gave: (6, 128, 384).

**Comment by neil454** [comment]
Please refer to this [comment](https://github.com/neil454/deep-motion/issues/2#issuecomment-283479980).
